name: Blog README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 AM GST
    - cron: '0 20 * * *'

jobs:
  update-readme:
    name: Update GR8z README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dohad.dev/feed.xml'
