name: WakaTime README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 AM GST
    - cron: '0 20 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Daily stats update
