name: WakaTime README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am GST
    - cron: '0 8 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: false
          SHOW_COMMIT: false
          SHOW_EDITORS: false
          SHOW_LOC_CHART: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE_PER_REPO: false
