name: WakaTime README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 AM GST
    - cron: '0 20 * * *'

jobs:
  update-readme:
    name: Update GR8z README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: False
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_COMMIT: False
          SHOW_LANGUAGE: False
          SHOW_LANGUAGE_PER_REPO: False
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dohad.dev/feed.xml'
