name: WakaTime README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 AM GST
    - cron: '0 20 * * *'

jobs:
  update-readme:
    name: Update GR8z README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Daily stats update
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
